name: example-environment
channels:
  - conda-forge
dependencies:
  - gravipy
  - python
  - jupyterlab
  - nodejs
  - nbconvert
  - widgetsnbextension
  - numpy
  - k3d
  - pip
  - sqlalchemy
  - sympy
  - nbgrader
  - scikit-learn
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
